FROM node:20
WORKDIR /app

ENV CI=true \
    CHOKIDAR_USEPOLLING=true \
    HOST=0.0.0.0 \
    NUXT_HOST=0.0.0.0 \
    NUXT_PORT=3001

COPY package*.json ./
RUN npm install

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
