services:
  # Expose database port for local development
  db:
    ports:
      - '5433:5432'

  # Expose Redis port for local development
  redis:
    ports:
      - '6380:6379'

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://taskforge:taskforge@db:5432/taskforge
      - REDIS_URL=redis://redis:6379
    ports:
      - '2999:2999'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3001
      - NUXT_API_BASE=http://api:2999/api
      - NUXT_PUBLIC_API_BASE=http://localhost:2999/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    command: npm run dev
    depends_on:
      - api
