services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskforge
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/taskforge?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 2999
      NODE_ENV: development
    depends_on:
      - db
      - redis
    ports:
      - '2999:2999'
      - '5555:5555'
    command: npm run start:dev

volumes:
  db_data:
  redis_data:
