services:
  # Expose Redis port for local development
  redis:
    ports:
      - '6380:6379'

  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/backend:/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - '2999:2999'
    depends_on:
      redis:
        condition: service_healthy
    command: npm run start:dev

  frontend:
    build:
      context: ./apps/vue
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3001
      - NUXT_API_BASE=http://api:2999/api
      - NUXT_PUBLIC_API_BASE=http://localhost:2999/api
    volumes:
      - ./apps/vue:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    command: npm run dev
    depends_on:
      - api
